### ISSUE TITLE
chaining `select` and `nest` causes segfault (dplyr 0.4.3 tidyr 0.4.1)

### ISSUE THREAD

**Issue by ashander** [hadley/tidyr#181] opened 2016-04-13 17:34 UTC
to reproduce 

`iris %>% select(1:2) %>% nest(1:2)`

```
 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .Call("dplyr_distinct_impl", PACKAGE = "dplyr", df, vars)
 2: distinct_impl(dist$data, dist$vars)
 3: distinct_.data.frame(dplyr::select_(data, .dots = group_cols))
 4: dplyr::distinct_(dplyr::select_(data, .dots = group_cols))
 5: nest_impl(data, key_col, group_cols, nest_cols)
 6: nest_.data.frame(data, key_col, nest_cols)
 7: nest_(data, key_col, nest_cols)
 8: nest(., 1:2)
 9: function_list[[k]](value)
10: withVisible(function_list[[k]](value))
11: freduce(value, `_function_list`)
12: `_fseq`(`_lhs`)
13: eval(expr, envir, enclos)
14: eval(quote(`_fseq`(`_lhs`)), env, env)
15: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
16: iris %>% select(1:2) %>% nest(1:2)
```

**Comment by hadley** [comment] 2016-05-16 20:19
Duplicate of #186

**Closed by hadley** 2016-05-16 20:19 UTC
