### ISSUE TITLE
please alert when completing over group_by variable

### ISSUE THREAD

**Issue by mplourde** [hadley/tidyr#166] opened 2016-02-18 19:36 UTC
Currently nothing happens when you `complete` on variables that are part of an existing group_by:

```{r}
data_frame(a=c(1,2,3), b=c(1,1,2)) %>% group_by(a) %>% complete(a, b)
# Source: local data frame [3 x 2]
# 
#       a     b
#   (dbl) (dbl)
# 1     1     1
# 2     2     1
# 3     3     2
```

Could `complete` and `complete_` raise an error in this situation or at least issue a warning?

**Comment by hadley** [comment] 2016-05-16 20:36
Duplicate of #167

**Closed by hadley** 2016-05-16 20:36 UTC
