### ISSUE TITLE
spreading with no ID columns

### ISSUE THREAD

**Issue by bramtayl** [hadley/tidyr#142] opened 2015-11-25 01:49 UTC
When spreading with no ID columns, everything ends up in a separate row, where as it would seem more intuitive to all end up in the same row:

```{r}
data_frame(variable = c("a", "b", "c"),
           value = c(1, 2, 3) ) %>%
  spread(variable, value)

# expected result
data_frame(a = 1, b = 2, c = 3)
```

**Comment by hadley** [comment] 2015-12-30 22:31
Duplicate of #41

**Closed by hadley** 2015-12-30 22:31 UTC

**Comment by hadley** [comment] 2015-12-30 22:42
And now fixed :)
