### ISSUE TITLE
unite already existing variable names

### ISSUE THREAD

**Issue by bramtayl** [hadley/tidyr#140] opened 2015-11-21 16:22 UTC
When you want to unite and make the resulting column name match an already existing column name, all the columns disappear.

```{r}
data_frame(
  a = c(1, 2),
  b = c(2, 1) ) %>%
  unite(a, a, b)

# results in 
data_frame()
```

**Comment by hadley** [comment] 2015-12-30 19:37
Duplicate of #89, and it's now fixed.

**Closed by hadley** 2015-12-30 19:37 UTC
